#include "ScreenView.h"
#include "core/CPUCore.h"
#include <iostream>
#include <fstream>
#include <unordered_map>
#include <mutex>
#include <cstdlib>

// Global map to track all manually created processes so we can re-attach to them later.
std::unordered_map<std::string, Process*> g_processMap;
std::mutex g_processMapMutex;

Process* getProcess(const std::string& name) {
    std::lock_guard<std::mutex> lock(g_processMapMutex);
    auto it = g_processMap.find(name);
    if (it != g_processMap.end()) {
        return it->second;
    }
    return nullptr;
}

Process* createProcess(const std::string& name, Scheduler& sched, uint32_t minIns, uint32_t maxIns) {
    Process* p = new Process();
    p->processName = name;
    p->pid = nextPid++;
    p->state = ProcessState::READY;
    p->programCounter = 0;
    p->timestamp = getTimestamp();

    // Determine a random number of instructions based on config limits
    uint32_t numIns = minIns;
    if (maxIns > minIns) {
        numIns = minIns + (std::rand() % (maxIns - minIns + 1));
    }

    // Populate with dummy PRINT instructions
    Instruction printInst = { InstructionType::PRINT, "", "" };
    for (uint32_t i = 0; i < numIns; i++) {
        p->instructions.push_back(printInst);
    }

    // Store in our tracking map
    {
        std::lock_guard<std::mutex> lock(g_processMapMutex);
        g_processMap[name] = p;
    }

    // Push to the actual scheduler
    enqueue(sched, *p);
    sched.cv.notify_one();

    return p;
}

void openProcessScreen(Process* p) {
    // Clear screen and move cursor to top-left using ANSI
    std::cout << "\033[2J\033[1;1H"; 
    
    bool inScreen = true;
    std::string cmd;

    while (inScreen && running) {
        std::cout << "process " << p->processName << ":\\> ";
        std::getline(std::cin, cmd);

        if (cmd == "exit") {
            inScreen = false;
            // Clear screen again to prep for returning to main console
            std::cout << "\033[2J\033[1;1H"; 
        }
        else if (cmd == "process-smi") {
            std::cout << "\nProcess name: " << p->processName << "\n";
            std::cout << "ID: " << p->pid << "\n\n";
            std::cout << "Logs:\n";

            // Open the log file generated by Process.cpp's executeInstruction
            std::ifstream logFile(p->processName + ".txt");
            if (logFile.is_open()) {
                std::string line;
                while (std::getline(logFile, line)) {
                    // Filter out the static header lines from Process.cpp so we only print active logs
                    if (line.find("Process name:") == std::string::npos &&
                        line.find("Logs:") == std::string::npos &&
                        !line.empty()) {
                        std::cout << line << "\n";
                    }
                }
            }

            if (p->state == ProcessState::FINISHED) {
                std::cout << "\nFinished!\n";
            }

            std::cout << "\nCurrent instruction line: " << p->programCounter << "\n";
            std::cout << "Lines of code: " << p->instructions.size() << "\n\n";
        }
        else if (!cmd.empty()) {
            std::cout << "Unknown command. Try 'process-smi' or 'exit'.\n";
        }
    }
}